#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.

## Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Dragon"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Dragonbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Dragonbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Dragon.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
#jgmenu_run gtktheme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
jgmenu_run init --apply-obtheme >/dev/null 2>&1

## Change xfce4-terminal theme
#xfce4-term-colors fane
xfconf-query -c xfce4-terminal -p /color-background -s "#181819191a1a"
xfconf-query -c xfce4-terminal -p /color-foreground -s "#d9d9d9d9d7d7"
xfconf-query -c xfce4-terminal -p /color-palette -s "rgb(4,4,4);rgb(214,69,69);rgb(0,173,111);rgb(227,184,86);rgb(53,141,204);rgb(199,80,179);rgb(16,156,156);rgb(212,212,212);rgb(158,165,171);rgb(255,99,99);rgb(94,224,154);rgb(255,224,102);rgb(82,151,199);rgb(245,122,225);rgb(121,224,216);rgb(224,224,224)"

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-dragon.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi" >/dev/null 2>&1
sed -i 's/^@theme "rounded.*/@theme "rounded-dragon.rasi"/g' "$HOME/.config/rofi/config.rasi" >/dev/null 2>&1

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
